// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cmeszgdsmqometnhnmbk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNtZXN6Z2RzbXFvbWV0bmhubWJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NDU1MDAsImV4cCI6MjA2OTQyMTUwMH0.M6_0MOFqr0SPMx1AIDM-HXyjqxWvaBqQILgQ6xO3I9U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});